"""empty message

Revision ID: f43c7d122b3c
Revises: a66c68168f2e
Create Date: 2018-03-30 23:08:57.760422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43c7d122b3c'
down_revision = 'a66c68168f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('etag_audio', sa.String(), nullable=True))
    op.add_column('result', sa.Column('s3_audio_key', sa.String(), nullable=True))
    op.add_column('result', sa.Column('slap_type', sa.String(), nullable=True))
    op.add_column('result', sa.Column('weather', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'weather')
    op.drop_column('result', 'slap_type')
    op.drop_column('result', 's3_audio_key')
    op.drop_column('result', 'etag_audio')
    # ### end Alembic commands ###
